### ISSUE TITLE
Creating Analytics Suite

### ISSUE THREAD

**Issue by jakebruemmer** [vbudhram/fantasy-football-io#3]
Hi,

Saw your project after thinking of writing a similar project myself for ESPN. Would you want to collaborate on making an analytics suite for this package? I'm thinking like league-specific analytics (perfect for leagues that last for more than 3 years).

**Comment by vbudhram** [comment]
Hey Jake,

Unfortunately I can not take on any more projects at this time. Feel free to use and extend any of the source code here! Best of luck this year!
